name: soft_cli_sample
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_svg: ^2.0.9
  dio: ^5.0.2
  retrofit: ^4.0.1
  logger: ^2.0.2+1
  money_formatter: ^0.0.3
  intl: ^0.18.1
  cached_network_image: ^3.2.1
  connectivity: ^3.0.6
  equatable: ^2.0.3
  package_info_plus: ^5.0.1
  pub_semver: ^2.1.1
  launch_review: ^3.0.1
  notification_permissions: ^0.6.1
  easy_localization: ^3.0.2-dev
#  firebase_messaging:
#  firebase_core: ^2.4.1
  permission_handler: ^11.2.0
  geolocator: ^10.1.0
  geolocator_android: ^4.1.7
  photo_view: ^0.14.0
  photo_manager: ^2.1.4
  camera: ^0.10.0
  path_provider: ^2.0.11
  carousel_slider: ^4.1.1
  lottie: ^3.0.0
  vibration: ^1.7.6
  flutter_svg_provider: ^1.0.3
  flutter_screenutil: ^5.6.1
  auto_size_text: ^3.0.0
  animate_do: ^3.0.2
  repo_annotation:
    git:
      url: https://github.com/alphaSoft99/repo_annotation.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.2.18
  freezed: ^2.2.0
  build_runner: ^2.3.3
  bloc_test: ^9.0.3
  hive_generator: ^2.0.0
  retrofit_generator: any
  platform: ^3.1.0
  mockito: ^5.2.0

flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/font/
    - assets/locale/
    - assets/lottie/

  fonts:
    - family: muller
      fonts:
        - asset: assets/font/muller/muller_bold.ttf
          weight: 900
        - asset: assets/font/muller/muller_extra_bold.ttf
          weight: 800
        - asset: assets/font/muller/muller_extra_bold.ttf
          weight: 700
        - asset: assets/font/muller/muller_extra_bold.ttf
          weight: 600
        - asset: assets/font/muller/muller_medium.ttf
          weight: 500
        - asset: assets/font/muller/muller_medium.ttf
          weight: 400
        - asset: assets/font/muller/muller_thin.ttf
          weight: 300
        - asset: assets/font/muller/muller_thin.ttf
          weight: 200
        - asset: assets/font/muller/muller_thin.ttf
          weight: 100

#dependency_overrides:
#  firebase_core_platform_interface: 4.5.1
