class Constants {
  Constants._();

  static const appName = 'NoInSoft';
  static const androidApp = 'noinsoft_android';
  static const iosAppId = '';
  static const baseUrl = "https://as/api";
  static const baseFileUrl = "http://as/";
  static const notificationIcon = "@mipmap/ic_launcher";
  static const language = "language";
  static const location = "location";
  static const lat = "lat";
  static const lng = "lng";
  static const localePath = "assets/locale";
  static const hasUser = "has_user";
  static const credentialsBox = "credentials_box";
  static const id = 'id';
  static const screen = 'screen';
  static const title = 'title';
  static const body = 'body';
  static const page = 'page';
  static const news = 'news';
  static const notificationSound = 'notificationSound';
  static const dateFormat = 'dd-MM-yyyy';
  static const phoneMask = '## ### ## ##';
  static const phonePrefix = '+998 ';
  static const phoneSeparator = ' ';
  static const error = "Error";
  static const html = 'html';
  static const space = ' ';
  static const plus = '+';
  static const uz = 'uz';
  static const ru = 'ru';
  static const en = 'en';
  static const defaultVersion = "1.0.0";
  static const dioTimeOut = 30000;
  static const animationDuration = 500;
  static const animationDelay = 100;
  static const empty = '';
  static const dialogOpacity = .5;
  static const textScaleFactor = 1.0;
  static const introCount = 3;
  static const smsCodeLength = 6;
  static const expansionFactor = 2.0;
}
